"""Первый запуск

Revision ID: 9b5f77401114
Revises: 
Create Date: 2026-06-21 16:34:28.299623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5f77401114'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_Admin_admin_id'), 'Admin', ['admin_id'], unique=False)
    op.create_table('Category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_Category_category_id'), 'Category', ['category_id'], unique=False)
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_f_name', sa.String(length=30), nullable=False),
    sa.Column('user_l_name', sa.String(length=30), nullable=False),
    sa.Column('user_phone', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('user_hashed_password', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=False)
    op.create_table('Order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purchase_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_Order_order_id'), 'Order', ['order_id'], unique=False)
    op.create_index(op.f('ix_Order_user_id'), 'Order', ['user_id'], unique=False)
    op.create_table('Parent_Product',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=50), nullable=False),
    sa.Column('parent_sex', sa.String(length=10), nullable=False),
    sa.Column('parent_community', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    op.create_index(op.f('ix_Parent_Product_category_id'), 'Parent_Product', ['category_id'], unique=False)
    op.create_index(op.f('ix_Parent_Product_parent_id'), 'Parent_Product', ['parent_id'], unique=False)
    op.create_index(op.f('ix_Parent_Product_user_id'), 'Parent_Product', ['user_id'], unique=False)
    op.create_table('Salesman_Data',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sale_iin', sa.String(length=20), nullable=False),
    sa.Column('sale_biin', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_Salesman_Data_sale_biin'), 'Salesman_Data', ['sale_biin'], unique=False)
    op.create_index(op.f('ix_Salesman_Data_sale_id'), 'Salesman_Data', ['sale_id'], unique=False)
    op.create_index(op.f('ix_Salesman_Data_sale_iin'), 'Salesman_Data', ['sale_iin'], unique=False)
    op.create_index(op.f('ix_Salesman_Data_user_id'), 'Salesman_Data', ['user_id'], unique=False)
    op.create_table('Variant',
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('var_order', sa.Integer(), nullable=False),
    sa.Column('var_image_url', sa.String(length=40), nullable=False),
    sa.Column('var_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['Parent_Product.parent_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('var_id'),
    sa.UniqueConstraint('user_id', 'parent_id', 'var_order', name='description_parent_salesman')
    )
    op.create_index(op.f('ix_Variant_parent_id'), 'Variant', ['parent_id'], unique=False)
    op.create_index(op.f('ix_Variant_user_id'), 'Variant', ['user_id'], unique=False)
    op.create_index(op.f('ix_Variant_var_id'), 'Variant', ['var_id'], unique=False)
    op.create_index(op.f('ix_Variant_var_order'), 'Variant', ['var_order'], unique=False)
    op.create_table('Attribute',
    sa.Column('att_id', sa.Integer(), nullable=False),
    sa.Column('var_id', sa.Integer(), nullable=True),
    sa.Column('att_name', sa.String(length=40), nullable=False),
    sa.Column('att_value', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['var_id'], ['Variant.var_id'], ),
    sa.PrimaryKeyConstraint('att_id')
    )
    op.create_index(op.f('ix_Attribute_att_id'), 'Attribute', ['att_id'], unique=False)
    op.create_index(op.f('ix_Attribute_var_id'), 'Attribute', ['var_id'], unique=False)
    op.create_table('Cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cart_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['var_id'], ['Variant.var_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_index(op.f('ix_Cart_cart_id'), 'Cart', ['cart_id'], unique=False)
    op.create_index(op.f('ix_Cart_user_id'), 'Cart', ['user_id'], unique=False)
    op.create_index(op.f('ix_Cart_var_id'), 'Cart', ['var_id'], unique=False)
    op.create_table('Order_Item',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('var_id', sa.Integer(), nullable=True),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], ),
    sa.ForeignKeyConstraint(['var_id'], ['Variant.var_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_Order_Item_order_id'), 'Order_Item', ['order_id'], unique=False)
    op.create_index(op.f('ix_Order_Item_order_item_id'), 'Order_Item', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_Order_Item_var_id'), 'Order_Item', ['var_id'], unique=False)
    op.create_table('Stock',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['var_id'], ['Variant.var_id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index(op.f('ix_Stock_stock_id'), 'Stock', ['stock_id'], unique=False)
    op.create_index(op.f('ix_Stock_var_id'), 'Stock', ['var_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Stock_var_id'), table_name='Stock')
    op.drop_index(op.f('ix_Stock_stock_id'), table_name='Stock')
    op.drop_table('Stock')
    op.drop_index(op.f('ix_Order_Item_var_id'), table_name='Order_Item')
    op.drop_index(op.f('ix_Order_Item_order_item_id'), table_name='Order_Item')
    op.drop_index(op.f('ix_Order_Item_order_id'), table_name='Order_Item')
    op.drop_table('Order_Item')
    op.drop_index(op.f('ix_Cart_var_id'), table_name='Cart')
    op.drop_index(op.f('ix_Cart_user_id'), table_name='Cart')
    op.drop_index(op.f('ix_Cart_cart_id'), table_name='Cart')
    op.drop_table('Cart')
    op.drop_index(op.f('ix_Attribute_var_id'), table_name='Attribute')
    op.drop_index(op.f('ix_Attribute_att_id'), table_name='Attribute')
    op.drop_table('Attribute')
    op.drop_index(op.f('ix_Variant_var_order'), table_name='Variant')
    op.drop_index(op.f('ix_Variant_var_id'), table_name='Variant')
    op.drop_index(op.f('ix_Variant_user_id'), table_name='Variant')
    op.drop_index(op.f('ix_Variant_parent_id'), table_name='Variant')
    op.drop_table('Variant')
    op.drop_index(op.f('ix_Salesman_Data_user_id'), table_name='Salesman_Data')
    op.drop_index(op.f('ix_Salesman_Data_sale_iin'), table_name='Salesman_Data')
    op.drop_index(op.f('ix_Salesman_Data_sale_id'), table_name='Salesman_Data')
    op.drop_index(op.f('ix_Salesman_Data_sale_biin'), table_name='Salesman_Data')
    op.drop_table('Salesman_Data')
    op.drop_index(op.f('ix_Parent_Product_user_id'), table_name='Parent_Product')
    op.drop_index(op.f('ix_Parent_Product_parent_id'), table_name='Parent_Product')
    op.drop_index(op.f('ix_Parent_Product_category_id'), table_name='Parent_Product')
    op.drop_table('Parent_Product')
    op.drop_index(op.f('ix_Order_user_id'), table_name='Order')
    op.drop_index(op.f('ix_Order_order_id'), table_name='Order')
    op.drop_table('Order')
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Category_category_id'), table_name='Category')
    op.drop_table('Category')
    op.drop_index(op.f('ix_Admin_admin_id'), table_name='Admin')
    op.drop_table('Admin')
    # ### end Alembic commands ###
